export const GET_LANDING_PRODUCTS_REQUEST = "GET_LANDING_PRODUCTS_REQUEST";
export const GET_LANDING_PRODUCTS_SUCCESS = "GET_LANDING_PRODUCTS_SUCCESS";
export const GET_LANDING_PRODUCTS_FAILURE = "GET_LANDING_PRODUCTS_FAILURE";
